config/routes.rb
Rails.application.routes.draw do
  
  resources :consulta

  resources :receta

  resources :registros

  devise_for :users
  
  root 'welcome#homepage'

  get 'welcome/homepage'
  
  get 'start/index'
  

end

app/models/consultum.rb
class Consultum < ActiveRecord::Base
end

app/models/recetum.rb
class Recetum < ActiveRecord::Base
end

app/models/registro.rb
class Registro < ActiveRecord::Base

	# attr_accessible :Nombre, :Segundo_Nombre, :Apellido_Paterno, :Apellido_Materno, :Telefono_principal, :Celular, :Email, :Ocupacion, :Fecha_de_Nacimiento, :Direccion, :Codigo_Postal, :Ciudad, :Estado

	# def self.search(search)
	# 	# return where('FALSE') if search.blank?

	# 	search_columns = [:Nombre, :Segundo_Nombre, :Apellido_Paterno, :Apellido_Materno, :Telefono_principal, :Celular, :Email, :Ocupacion, :Fecha_de_Nacimiento, :Direccion, :Codigo_Postal, :Ciudad, :Estado]
	# 	search.split('').each do |word|
	# 		search_columns.each do |column|
	# 			conditions << " lower(#{colum}) LIKE lower(#{sanitize("%#{word}%")}) "
	# 		end
	# 	end

		# conditions = conditions.join('OR')
		# self.where(conditions)

	def self.search(search)
		key = "%#{search}%"
    if search
      where(["Nombre LIKE :search OR Segundo_Nombre LIKE :search OR Apellido_Paterno LIKE :search OR Apellido_Materno LIKE :search OR Telefono_principal LIKE :search OR Celular LIKE :search OR Email LIKE :search OR Ocupacion LIKE :search OR Fecha_de_Nacimiento LIKE :search OR Direccion LIKE :search OR Codigo_Postal LIKE :search OR Ciudad LIKE :search OR Estado LIKE :search", search: key])
    else
      all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/consulta_controller.rb
class ConsultaController < ApplicationController
  before_action :set_consultum, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @consulta = Consultum.all
    respond_with(@consulta)
  end

  def show
    respond_with(@consultum)
  end

  def new
    @consultum = Consultum.new
    respond_with(@consultum)
  end

  def edit
  end

  def create
    @consultum = Consultum.new(consultum_params)
    @consultum.save
    respond_with(@consultum)
  end

  def update
    @consultum.update(consultum_params)
    respond_with(@consultum)
  end

  def destroy
    @consultum.destroy
    respond_with(@consultum)
  end

  private
    def set_consultum
      @consultum = Consultum.find(params[:id])
    end

    def consultum_params
      params.require(:consultum).permit(:Motivo_Consulta, :Diagnostico, :TX, :Labs, :Observaciones)
    end
end

app/controllers/receta_controller.rb
class RecetaController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recetum, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @receta = Recetum.all
    respond_with(@receta)
  end

  def show
    respond_with(@recetum)
  end

  def new
    @recetum = Recetum.new
    respond_with(@recetum)
  end

  def edit
  end

  def create
    @recetum = Recetum.new(recetum_params)
    @recetum.save
    respond_with(@recetum)
  end

  def update
    @recetum.update(recetum_params)
    respond_with(@recetum)
  end

  def destroy
    @recetum.destroy
    respond_with(@recetum)
  end

  private
    def set_recetum
      @recetum = Recetum.find(params[:id])
    end

    def recetum_params
      params.require(:recetum).permit(:Receta)
    end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_registro, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @registros = Registro.search(params[:search])
    # respond_with(@registros)
  end

  def show
    respond_with(@registro)
  end

  def new
    @registro = Registro.new
    respond_with(@registro)
  end

  def edit
  end

  def create
    @registro = Registro.new(registro_params)
    @registro.save
    respond_with(@registro)
  end

  def update
    @registro.update(registro_params)
    respond_with(@registro)
  end

  def destroy
    @registro.destroy
    respond_with(@registro)
  end

  private
    def set_registro
      @registro = Registro.find(params[:id])
    end

    def registro_params
      params.require(:registro).permit(:Nombre, :Segundo_Nombre, :Apellido_Paterno, :Apellido_Materno, :Telefono_principal, :Celular, :Email, :Ocupacion, :Fecha_de_Nacimiento, :Direccion, :Codigo_Postal, :Ciudad, :Estado)
    end

    def search_params
      params.require(:search).permit(:Nombre, :Segundo_Nombre, :Apellido_Paterno, :Apellido_Materno, :Telefono_principal, :Celular, :Email, :Ocupacion, :Fecha_de_Nacimiento, :Direccion, :Codigo_Postal, :Ciudad, :Estado)
    end

end

app/controllers/start_controller.rb
class StartController < ApplicationController
  before_action :authenticate_user!
  def index
  	render layout: "start"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def homepage
  	if user_signed_in?
  		redirect_to start_index_path
  	else
  		render layout: "homepage" 
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/helpers/receta_helper.rb
module RecetaHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/consulta/_form.html.erb
<%= simple_form_for(@consultum) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Motivo_Consulta %>
    <%= f.input :Diagnostico %>
    <%= f.input :TX %>
    <%= f.input :Labs %>
    <%= f.input :Observaciones %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/consulta/edit.html.erb
<div class="page-header">
  <%= link_to consulta_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @consultum, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing consultum</h1>
</div>

<%= render 'form' %>

app/views/consulta/index.html.erb
<div class="page-header">
  <%= link_to new_consultum_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Consultum
  <% end %>
  <h1>Listing consulta</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Motivo consulta</th>
            <th>Diagnostico</th>
            <th>Tx</th>
            <th>Labs</th>
            <th>Observaciones</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @consulta) do |consultum| %>
            <td><%= consultum.Motivo_Consulta %></td>
            <td><%= consultum.Diagnostico %></td>
            <td><%= consultum.TX %></td>
            <td><%= consultum.Labs %></td>
            <td><%= consultum.Observaciones %></td>
            <td><%= link_to 'Show', consultum %></td>
        <td><%= link_to 'Edit', edit_consultum_path(consultum) %></td>
        <td><%= link_to 'Destroy', consultum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/consulta/new.html.erb
<div class="page-header">
  <%= link_to consulta_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New consultum</h1>
</div>

<%= render 'form' %>

app/views/consulta/show.html.erb
<div class="page-header">
  <%= link_to consulta_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_consultum_path(@consultum), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show consultum</h1>
</div>

<dl class="dl-horizontal">
  <dt>Motivo consulta:</dt>
  <dd><%= @consultum.Motivo_Consulta %></dd>

  <dt>Diagnostico:</dt>
  <dd><%= @consultum.Diagnostico %></dd>

  <dt>Tx:</dt>
  <dd><%= @consultum.TX %></dd>

  <dt>Labs:</dt>
  <dd><%= @consultum.Labs %></dd>

  <dt>Observaciones:</dt>
  <dd><%= @consultum.Observaciones %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sistema para Gestión de Clínicas Médicas">
    <meta name="author" content="Carlos Gomez">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  	<%= javascript_include_tag 'data-turbolinks-track' => true %> <!-- aplication -->

  	<%= csrf_meta_tags %>
    <title>Consultorio Virtual</title>

    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "freelancer" %>
    <%= stylesheet_link_tag "font-awesome" %>

    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
</head>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <%= link_to 'Medicus', start_index_path, :class => 'navbar-brand' %>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <p class="navbar-text pull-right">
                    <% if user_signed_in? %>Bienvenido <%= current_user.email %>
                    <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
                    <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                    <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
                    <%= link_to "Ingresar", new_user_session_path, :class => 'navbar-link'  %>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    
    <!-- Contenido -->

		<%= yield %>
    <!-- ./Contenido -->
   
<!-- Footer del layout -->
<hr />
<div class="container footer-simple">
  <div class="row">
    <div class="col-lg-12 text-center text-muted">
      Derechos Reservados <i class="fa fa-copyright"></i>, Medicus 2015 | <i class="fa fa-code"></i> con <i class="fa fa-heart"></i>
    </div>
  </div>
</div>
<!-- ./Footer del layout -->
    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visible-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>


</body>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "bootstrap" %>
    <%= javascript_include_tag "classie" %>
    <%= javascript_include_tag "cbpAnimatedHeader" %>
    <!-- JS omitidos -->
    <!-- jqBootstrapValidation, contact_me -->
    <%= javascript_include_tag "freelancer" %>
</html>

app/views/layouts/start.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sistema para Gestión de Clínicas Médicas">
    <meta name="author" content="Carlos Gomez">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'data-turbolinks-track' => true %> <!-- aplication -->
  	<%= csrf_meta_tags %>
    <title>Consultorio Virtual</title>

    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "freelancer" %>
    <%= stylesheet_link_tag "font-awesome" %>

    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">Medicus</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <p class="navbar-text pull-right">
                    <% if user_signed_in? %>Bienvenido <%= current_user.email %>
                    <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
                    <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                    <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
                    <%= link_to "Ingresar", new_user_session_path, :class => 'navbar-link'  %>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    
    <!-- Contenido -->
		<%= yield %>
    <!-- ./Contenido -->
   
<!-- Footer del layout -->
<hr />
<div class="container footer-simple">
  <div class="row">
    <div class="col-lg-12 text-center text-muted">
      Derechos Reservados <i class="fa fa-copyright"></i>, Medicus 2015 | <i class="fa fa-code"></i> con <i class="fa fa-heart"></i>
    </div>
  </div>
</div>
<!-- ./Footer del layout -->
    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visible-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

</body>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "bootstrap" %>
    <%= javascript_include_tag "classie" %>
    <%= javascript_include_tag "cbpAnimatedHeader" %>
    <%= javascript_include_tag "jqBootstrapValidation" %>
    <%= javascript_include_tag "contact_me" %>
    <%= javascript_include_tag "freelancer" %>
</html>

app/views/receta/_form.html.erb
<%= simple_form_for(@recetum) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Receta %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/receta/edit.html.erb
<div class="page-header">
  <%= link_to receta_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @recetum, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editar Receta</h1>
</div>

<%= render 'form' %>

app/views/receta/index.html.erb
<div class="page-header">
  <%= link_to new_recetum_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nueva Receta
  <% end %>
  <h1>Lista de Recetas</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Receta</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @receta) do |recetum| %>
            <td><%= recetum.Receta %></td>
            <td><%= link_to 'Show', recetum %></td>
        <td><%= link_to 'Edit', edit_recetum_path(recetum) %></td>
        <td><%= link_to 'Destroy', recetum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/receta/new.html.erb
<div class="page-header">
  <%= link_to receta_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Nueva Receta</h1>
</div>

<%= render 'form' %>

app/views/receta/show.html.erb
<div class="page-header">
  <%= link_to receta_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_recetum_path(@recetum), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Mostrar Receta</h1>
</div>

<dl class="dl-horizontal">
  <dt>Receta:</dt>
  <dd><%= @recetum.Receta %></dd>

</dl>

app/views/registros/edit.html.erb
<div class="page-header">
  <%= link_to registros_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <%= link_to @registro, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h2>Editar Registro de paciente</h2>
</div>

<%= render 'form' %>

app/views/registros/index.html.erb
<div class="wrap-registro">
  <!-- Search -->
  <div class="row search">
    <div class="col-xs-12 pull-right">
      <%= form_tag registros_path, :method => "get" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar paciente" %>
        </p>
        <p class="pull-right">
          <%= submit_tag "Buscar", class: 'btn btn-default' %>
        </p>
      <% end %>
    </div>
  </div>
  <!-- ./Search -->

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Nombre</th>
          <!-- <th>Segundo nombre</th>
          <th>Apellido paterno</th>
          <th>Apellido materno</th> -->
          <th>Telefono principal</th>
          <!-- <th>Celular</th> -->
          <th>Email</th>
          <!-- <th>Ocupacion</th>
          <th>Fecha de nacimiento</th>
          <th>Direccion</th>
          <th>Codigo postal</th>
          <th>Ciudad</th>
          <th>Estado</th> -->
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @registros) do |registro| %>
          <td><%= registro.Nombre %> <%= registro.Segundo_Nombre %> <%= registro.Apellido_Paterno %> <%= registro.Apellido_Materno %></td>
          <!-- <td></td>
          <td></td>
          <td></td> -->
          <td><%= registro.Telefono_principal %></td>
          <!-- <td><%= registro.Celular %></td> -->
          <td><%= registro.Email %></td>
          <!-- <td><%= registro.Ocupacion %></td>
          <td><%= registro.Fecha_de_Nacimiento %></td>
          <td><%= registro.Direccion %></td>
          <td><%= registro.Codigo_Postal %></td>
          <td><%= registro.Ciudad %></td>
          <td><%= registro.Estado %></td> -->
          <td><%= link_to 'Ver', registro, class: "btn btn-info" %></td>
          <!-- <td><%= link_to 'Editar', edit_registro_path(registro), class: "btn btn-warning" %></td>
          <td><%= link_to 'Eliminar', registro, class: "btn btn-danger", method: :delete, data: { confirm: 'Estas seguro de que quieres eliminar este registro?' } %></td> -->
        <% end %>
      </tbody>
    </table>
    
  </div>
  <div class="row">
      <div class="col-xs-4 page-header">
        <%= link_to new_registro_path, class: 'btn btn-success' do %>
          <span class="glyphicon glyphicon-plus"></span>
          Nuevo Paciente
        <% end %>
      </div>
    </div>
</div>

app/views/registros/new.html.erb
<div class="page-header">
  <%= link_to registros_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <h2>Ingresa los datos del paciente</h2>
</div>

<%= render 'form' %>

app/views/registros/show.html.erb
<div class="page-header">
  <%= link_to registros_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <%= link_to edit_registro_path(@registro), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Datos del Paciente</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nombre:</dt>
  <dd><%= @registro.Nombre %></dd>

  <dt>Segundo nombre:</dt>
  <dd><%= @registro.Segundo_Nombre %></dd>

  <dt>Apellido paterno:</dt>
  <dd><%= @registro.Apellido_Paterno %></dd>

  <dt>Apellido materno:</dt>
  <dd><%= @registro.Apellido_Materno %></dd>

  <dt>Telefono principal:</dt>
  <dd><%= @registro.Telefono_principal %></dd>

  <dt>Celular:</dt>
  <dd><%= @registro.Celular %></dd>

  <dt>Email:</dt>
  <dd><%= @registro.Email %></dd>

  <dt>Ocupacion:</dt>
  <dd><%= @registro.Ocupacion %></dd>

  <dt>Fecha de nacimiento:</dt>
  <dd><%= @registro.Fecha_de_Nacimiento %></dd>

  <dt>Direccion:</dt>
  <dd><%= @registro.Direccion %></dd>

  <dt>Codigo postal:</dt>
  <dd><%= @registro.Codigo_Postal %></dd>

  <dt>Ciudad:</dt>
  <dd><%= @registro.Ciudad %></dd>

  <dt>Estado:</dt>
  <dd><%= @registro.Estado %></dd>

</dl>

app/views/start/index.html.erb
<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Medicus", welcome_homepage_path, class: "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <!-- Login -->
                    <p class="navbar-text pull-right">
                    <% if user_signed_in? %>Bienvenido <%= current_user.email %>
                    <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
                    <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                    <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
                    <%= link_to "Ingresar", new_user_session_path, :class => 'navbar-link'  %>
                    <% end %>
                    <!-- /.login -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <!-- Inicio Grid Section -->
    <section id="start">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3 class="text-center">Dashboard</h3>
                </div>
                <div class="col-lg-12 text-center">
                Bienvenido Dr. <%= current_user.email %>
                </div>
            </div>
            <hr />

            <!-- espacio de search -->

            <div class="row">
                <div class="col-sm-4 start-item">
                    <div class="page-header">
                        <%= image_tag ("cabin.png"), :alt=> "cabin", :title=>"cabin", :class=>"img-responsive" %>
    					<%= link_to new_registro_path, class: 'btn btn-success' do %>
    					    <span class="glyphicon glyphicon-plus"></span>
    					       Nuevo Paciente
    					<% end %>
    				</div>
                </div>
                <div class="col-sm-4 start-item">
                    <div class="page-header">
                        <%= image_tag ("cabin.png"), :alt=> "cabin", :title=>"cabin", :class=>"img-responsive" %>
    					<%= link_to registros_path, class: 'btn btn-success' do %>
    						<span class="glyphicon glyphicon-search"></span>
    							Pacientes Ingresados
    					<% end %>
    				</div>
                </div>
                <div class="col-sm-4 start-item">
                    <div class="page-header">
                        <%= image_tag ("cabin.png"), :alt=> "cabin", :title=>"cabin", :class=>"img-responsive" %>
    					<%= link_to receta_path, class: 'btn btn-success' do %>
    						<span class="glyphicon glyphicon-list-alt"></span>
    							Generar Receta
    					<% end %>
    				</div>
                </div>
            </div>
        </div>
    </section>

</body>

</html>